### ISSUE TITLE
State Params Question

### ISSUE THREAD

**Issue by AlexAdach** [AlexBlackfrost/Unity-Hierarchical-Finite-State-Machine#1]
Hi. 

I really like how you're passing component references and state settings with the state.params class in the states for your battleroyal example. I'm a little confused by how you're not getting a null reference when you initialize the state machine. I don't see you instantiate the params classes anywhere? Sorry still relatively new...

**Comment by AlexBlackfrost** [comment]
Hi, thanks!

The params classes such as `AttackParams` are declared in `AnimalController.cs`. These classes have the `[Serializable]` attribute applied, which takes care of creating an instance of the class and serializing it on the inspector.

Hope it helps! Let me know if it fixed your problem.
